import express from "express";
import http from "http";
import { Server as SocketIOServer } from "socket.io";
import { spawn } from "child_process";
import fs from "fs";
import {pipeline} from "node:stream/promises";
import {Transform} from "node:stream";

const app=express();const server=http.createServer(app);const io=new SocketIOServer(server,{cors:{origin:"*"}});
const PORT=Number(process.env.PORT||10000),CONTROL_TOKEN=process.env.CONTROL_TOKEN||"change-me",TIKTOK_USERNAME=(process.env.TIKTOK_USERNAME||"takurada").replace(/^@/,"").trim();
const RTMP_SERVER=(process.env.RTMP_SERVER||"").trim(),RTMP_STREAM_KEY=(process.env.RTMP_STREAM_KEY||"").trim();
const mediaSources=JSON.parse(process.env.MEDIA_SOURCES||"{}");
const mediaRoot=process.env.MEDIA_ROOT||"/tmp/takarada-media";fs.mkdirSync(mediaRoot,{recursive:true});let playbackTest=true;
const videos=[["c6FAO3-zvhE","Lush Caves"],["AirXwBsNPDw","Rainy Riverside"],["wcIUiy_Ofcw","Ghibli Nostalgic"],["y8yMP36qHXA","Rainy Swamp"],["Zoq4ogt2wtU","Pine Forest House"],["Dy3VtjcHdCs","Rainy Cliff"],["ykHsq6yUNGg","Rainy Flower Forest"],["nUbDQ0wUESU","Medieval Farmhouse"],["snvLyjMcgh0","Rainy River"],["N6S53tOB1ss","Rainy Jungle Tree House"],["C_WaC-JmhFo","Rainy Mountain"],["eHSxedwXaM0","Rainy Cherry Grove"],["oCIpgdb2pM4","Rainy Mangrove Swamp"],["yTTutYKV1rk","Rainy Overgrown Laputa Part 1"],["2byiUUc0SnQ","Rainy Overgrown Laputa Part 2"],["UDRhiTUMVQY","Ghibli Nostalgic 1.20"],["wV9VatPiPf4","Rainy Spruce Island"],["LoeTtwvBD_k","Rainy Beach House"],["-DRRSTrLHTI","Rainy Greenhouse"],["bp-1X7sQ_2M","Rainy Cherry Lake"],["Ps0oA1nt3mw","Rainy Meadow"],["pW0iacBW1MU","Snowy Mountain"],["Az9X6YFzcBU","Christmas Snow Village"],["i9U-rUObowg","Rainy Mountain 1.21"],["IsXCRoImZ3c","Rainy Pale Garden"],["AepZzZS6j_U","Rainy Dark Forest"],["GFmBMg7-b44","Rainy Farmhouse"],["CIHsdaqCXwM","Rainy River Island"],["hYJY95sAeFc","Rainy Pale Cherry"],["O6yrzYkn2i8","Rainy Old Treehouse"]].map(([id,title])=>({id,title}));
let index=0,playing=true,ffmpeg=null,tiktokConnected=false,recentChat=[],recentEvents=[],speaking=false;let tiktokConnection=null,tiktokConnecting=false;let cloudPlayerState={code:-999,label:"waiting",videoId:null,updatedAt:0};
let broadcastWanted=false,broadcastStatus="stopped",broadcastError=null,broadcastStartedAt=null,lastChatReplyAt=0,recentFollower=null,recentGift=null;
app.use(express.json());app.use((req,res,next)=>{res.setHeader("Referrer-Policy","strict-origin-when-cross-origin");next()});app.use(express.static("public"));
function auth(req,res,next){const t=req.query.token||req.headers["x-control-token"];if(t!==CONTROL_TOKEN)return res.status(403).send("Bad control token");next()}
function getRtmp(){const direct=(process.env.RTMP_URL||"").trim();if(direct)return direct;if(!RTMP_SERVER||!RTMP_STREAM_KEY)return"";return RTMP_SERVER.replace(/\/$/,"")+"/"+RTMP_STREAM_KEY.replace(/^\//,"")}
function cur(){const video=videos[index];return {...video,sourceUrl:mediaSources[video.id]||null}}function state(){const current=playbackTest?{...cur(),title:"Cloud readiness test",sourceUrl:"/demo-gameplay.webm",test:true}:cur();return{index,count:videos.length,playing,current,next:videos[(index+1)%videos.length],broadcasting:!!ffmpeg,broadcastWanted,broadcastStatus,broadcastError,broadcastStartedAt,tiktokConnected,username:TIKTOK_USERNAME||null,cloudPlayerState,version:"astra-ready-3",rtmpConfigured:!!getRtmp(),mediaReady:!!current.sourceUrl&&!current.test,playbackTest,recentFollower,recentGift,chat:recentChat.slice(-8),events:recentEvents.slice(-8)}}
function nextVideo(d=1){index=(index+d+videos.length)%videos.length;playing=true;io.emit("queue",state())}
function addChat(user,text){const c={user,text,ts:Date.now()};recentChat.push(c);recentChat=recentChat.slice(-50);io.emit("chat",c)}
function speak(text){if(speaking||!text)return;speaking=true;const f=`/tmp/takarada-${Date.now()}.wav`;const synth=spawn("espeak-ng",["-v","en-us","-s","155","-p","48","-a","135","-w",f,text]);synth.on("close",()=>{const p=spawn("paplay",["--device=takarada",f]);const done=()=>{speaking=false;try{fs.unlinkSync(f)}catch{}};p.on("close",done);p.on("error",done)});synth.on("error",()=>{speaking=false})}
function addEvent(type,text,extra={}){const e={type,text,ts:Date.now(),...extra};recentEvents.push(e);recentEvents=recentEvents.slice(-50);io.emit("event",e);if(type==="commentary")speak(text);if(type==="follow")speak(`Thanks for the follow, ${extra.user||"friend"}.`);if(type==="gift")speak(`Thank you for the ${extra.gift||"gift"}, ${extra.user||"friend"}.`)}
function commentary(title){const t=title.toLowerCase();let p;if(t.includes("cave"))p=["These caves are actually coming together.","The lighting down here is clean.","I would absolutely get lost in this cave."];else if(t.includes("rain"))p=["The rain makes this build way more relaxing.","This is a good spot for a rainy build.","That roof is going to look good in this weather."];else if(t.includes("snow")||t.includes("christmas"))p=["This snow build is ridiculously cozy.","The winter atmosphere is perfect.","I like where this village is going."];else p=["That build is coming together.","I like this spot.","This is actually relaxing to watch."];return p[Math.floor(Math.random()*p.length)]}
function replyToComment(user,text){if(Date.now()-lastChatReplyAt<18000||!text?.trim())return;const t=text.toLowerCase();let reply;if(/hello|\bhi\b|hey/.test(t))reply=`Hey ${user}, welcome in.`;else if(/what|which|where|how/.test(t))reply=`Good question, ${user}. I am watching this build with you.`;else if(/love|nice|cool|great|amazing/.test(t))reply=`Glad you like it, ${user}.`;else if(Math.random()<.2)reply=`I see you, ${user}. Thanks for hanging out.`;if(reply){lastChatReplyAt=Date.now();addEvent("commentary",reply,{replyTo:user})}}
function safeBroadcastError(value,rtmp){return String(value||"").replaceAll(rtmp,"[TikTok destination]").replace(/rtmps?:\/\/\S+/gi,"[TikTok destination]").slice(-600)}
function scheduleBroadcastRetry(){if(!broadcastWanted)return;setTimeout(()=>{if(broadcastWanted&&!ffmpeg)startBroadcast(true)},12000).unref()}
function startBroadcast(retry=false){if(playbackTest){broadcastWanted=false;return{ok:false,message:"Readiness test is active. Full footage must be connected before TikTok broadcast."}};if(ffmpeg)return{ok:true,message:"Broadcast already running"};if(cloudPlayerState.label!=="playing"||Date.now()-cloudPlayerState.updatedAt>15000){if(!retry)broadcastWanted=false;return{ok:false,message:"Gameplay is not ready. Check the cloud player status before starting."}};const rtmp=getRtmp();if(!rtmp){if(!retry)broadcastWanted=false;return{ok:false,message:"TikTok streaming destination is not configured yet"}};broadcastWanted=true;broadcastStatus="starting";broadcastError=null;const w=process.env.STREAM_WIDTH||"720",h=process.env.STREAM_HEIGHT||"1280",fps=process.env.STREAM_FPS||"30";const args=["-hide_banner","-loglevel","warning","-thread_queue_size","1024","-f","x11grab","-draw_mouse","0","-framerate",fps,"-video_size",`${w}x${h}`,"-i",":99.0","-thread_queue_size","1024","-f","pulse","-i","takarada.monitor","-c:v","libx264","-preset","veryfast","-tune","zerolatency","-pix_fmt","yuv420p","-b:v","3500k","-maxrate","4000k","-bufsize","7000k","-g",String(Number(fps)*2),"-c:a","aac","-b:a","128k","-ar","44100","-f","flv",rtmp];ffmpeg=spawn("ffmpeg",args,{stdio:["ignore","ignore","pipe"]});let stderr="";ffmpeg.stderr.on("data",d=>{stderr=(stderr+String(d)).slice(-4000)});ffmpeg.on("spawn",()=>{broadcastStatus="streaming";broadcastStartedAt=Date.now();io.emit("status",state())});ffmpeg.on("error",e=>{broadcastError=safeBroadcastError(e.message,rtmp)});ffmpeg.on("exit",c=>{const wanted=broadcastWanted;ffmpeg=null;broadcastStartedAt=null;broadcastStatus=wanted?"reconnecting":"stopped";if(c&&!broadcastError)broadcastError=safeBroadcastError(stderr||`Encoder exited with code ${c}`,rtmp);io.emit("status",state());if(wanted)scheduleBroadcastRetry()});io.emit("status",state());return{ok:true,message:"Cloud encoder is connecting to TikTok"}}
function stopBroadcast(){broadcastWanted=false;broadcastStatus="stopped";broadcastError=null;broadcastStartedAt=null;if(!ffmpeg){io.emit("status",state());return{ok:true,message:"Broadcast already stopped"}};const processToStop=ffmpeg;ffmpeg=null;processToStop.kill("SIGTERM");io.emit("status",state());return{ok:true,message:"Cloud broadcast stopped"}}
async function connectTikTok(){
 if(!TIKTOK_USERNAME||tiktokConnected||tiktokConnecting)return;
 tiktokConnecting=true;
 try{
  const {TikTokLiveConnection,WebcastEvent,ControlEvent}=await import("tiktok-live-connector");
  const t=new TikTokLiveConnection(TIKTOK_USERNAME,{processInitialData:false});tiktokConnection=t;
  t.on(WebcastEvent.CHAT,d=>{const user=d.user?.uniqueId||d.uniqueId||d.user?.nickname||"viewer",text=d.comment||"";addChat(user,text);replyToComment(user,text);});
  t.on(WebcastEvent.FOLLOW,d=>{const user=d.user?.uniqueId||d.uniqueId||d.user?.nickname||"viewer";recentFollower={user,ts:Date.now()};addEvent("follow",user+" followed",{user});});
  t.on(WebcastEvent.GIFT,d=>{if(d.giftType===1&&!d.repeatEnd)return;const user=d.user?.uniqueId||d.uniqueId||d.user?.nickname||"viewer",gift=d.giftDetails?.giftName||d.giftName||"a gift";recentGift={user,gift,ts:Date.now()};addEvent("gift",user+" sent "+gift,{user,gift});});
  if(ControlEvent?.DISCONNECTED)t.on(ControlEvent.DISCONNECTED,()=>{tiktokConnected=false;io.emit("status",state());});
  if(ControlEvent?.ERROR)t.on(ControlEvent.ERROR,()=>{});
  await t.connect();tiktokConnected=true;io.emit("status",state());
 }catch(e){tiktokConnected=false;await tiktokConnection?.disconnect().catch(()=>{});console.log("TikTok connection waiting:",e?.message||String(e));}
 finally{tiktokConnecting=false;}
}
setInterval(connectTikTok,60000).unref();
app.get("/",(req,res)=>res.type("html").send('<meta name="viewport" content="width=device-width,initial-scale=1"><title>Takarada Control</title><body style="background:#090a0f;color:white;font:18px system-ui;padding:32px"><h1>Takarada Cloud Live</h1><p>Open your private control link to manage the stream.</p><a style="color:#ff5677" href="/preview">View layout preview</a></body>'));app.get("/stage",(req,res)=>res.sendFile(process.cwd()+"/public/stage.html"));app.get("/preview",(req,res)=>res.sendFile(process.cwd()+"/public/stage.html"));app.get("/control",auth,(req,res)=>res.sendFile(process.cwd()+"/public/control.html"));app.get("/api/state",(req,res)=>res.json(state()));
app.use("/media",express.static(mediaRoot));
app.put("/api/test-media",auth,async(req,res)=>{
 const file=mediaRoot+"/playback-test.mp4",temp=file+".upload";let size=0;
 if(fs.existsSync(temp))return res.status(409).json({ok:false,message:"Upload already in progress"});
 try{await pipeline(req,new Transform({transform(chunk,enc,cb){size+=chunk.length;cb(size>50*1024*1024?new Error("Test file exceeds 50MB"):null,chunk)}}),fs.createWriteStream(temp,{flags:"wx"}));fs.renameSync(temp,file);res.json({ok:true,size});}
 catch(e){try{fs.unlinkSync(temp)}catch{}if(!res.headersSent)res.status(400).json({ok:false,message:e.message});}
});
app.post("/api/player-state",auth,(req,res)=>{if(req.body?.renderer==="cloud"){cloudPlayerState={code:Number(req.body.code),label:String(req.body.label||"unknown"),error:req.body.error||null,position:Number(req.body.position||0),diagnostic:String(req.body.diagnostic||"").slice(0,1500),videoId:req.body.videoId||null,updatedAt:Date.now()};if(cloudPlayerState.error)console.log("cloud player error",cloudPlayerState.error)}res.json({ok:true})});
app.post("/api/action/:action",auth,(req,res)=>{const a=req.params.action;let r={ok:true,message:"OK"};if(a==="test-on"){playbackTest=true;playing=true;io.emit("queue",state());}else if(a==="test-off"){playbackTest=false;io.emit("queue",state());}else if(a==="reaction-test"){addEvent("commentary","Thanks for hanging out. This build is coming together.");r.message="Streamer reaction test played"}else if(a==="next")nextVideo(1);else if(a==="prev")nextVideo(-1);else if(a==="play"){playing=true;io.emit("playback",{playing})}else if(a==="pause"){playing=false;io.emit("playback",{playing})}else if(a==="start")r=startBroadcast();else if(a==="stop")r=stopBroadcast();else return res.status(404).json({ok:false,message:"Unknown action"});res.json({...r,state:state()})});app.post("/api/video-ended",auth,(req,res)=>{if(!playbackTest&&req.body.videoId===cur().id)nextVideo(1);res.json(state())});
app.get("/api/cloud-frame",auth,(req,res)=>{res.setHeader("Cache-Control","no-store");if(!fs.existsSync("/tmp/cloud-frame.jpg"))return res.status(503).send("Cloud frame not ready");res.sendFile("/tmp/cloud-frame.jpg")});
io.on("connection",s=>s.emit("status",state()));function scheduleComment(){setTimeout(()=>{if(playing&&cloudPlayerState.label==="playing")addEvent("commentary",commentary(cur().title));scheduleComment()},90000+Math.floor(Math.random()*110000))}scheduleComment();server.listen(PORT,"0.0.0.0",()=>{console.log(`Takarada cloud live on :${PORT}`);connectTikTok();if(process.env.AUTO_START==="true"&&process.env.RTMP_URL)setTimeout(startBroadcast,7000)});