import { generateStoryJson, hasGatewayAuth } from '../lib/ai-gateway.js';

const CHARACTER_PAIRS = [
  [{id:'A',name:'Marcus',voice:'onyx'},{id:'B',name:'Nia',voice:'nova'}],
  [{id:'A',name:'Eli',voice:'echo'},{id:'B',name:'Tessa',voice:'shimmer'}],
  [{id:'A',name:'Andre',voice:'onyx'},{id:'B',name:'Maya',voice:'nova'}],
  [{id:'A',name:'Caleb',voice:'echo'},{id:'B',name:'Renee',voice:'shimmer'}]
];

const SAFE_ACTIONS = ['point','step-back','reach','knock','open-door','slam-door','look','turn','phone','run','freeze','hand-object','pull','gesture','laugh','handshake','hide','walk','wave'];
const SAFE_SETTINGS = ['hallway','kitchen','apartment','laundromat','elevator','lobby','bus','street','shop','office','garage','cafe','motel','bedroom','park'];
const DAILY_DURATION_MINUTES = [2.5,3.25,4.25,5.25,6.75,8.5];

const PREMISES = [
  {genre:'horror',title:'The Elevator Found Floor Zero',setting:'elevator',hook:'A floor-zero button appears in an office elevator after midnight.',beats:['They press it by accident.','The doors open to a duplicate lobby with no people.','Two visitor badges show their names and tomorrow’s date.','Security monitors show the real building losing floors one by one.','They realize the duplicate building is replacing the original.','They return upstairs, but a reflection exits the elevator before they do.']},
  {genre:'mystery',title:'The Dryer Returned Tomorrow',setting:'laundromat',hook:'A dryer contains the exact clothes they are currently wearing.',beats:['A receipt inside is dated tomorrow.','One jacket pocket contains a warning in familiar handwriting.','Every machine starts counting down together.','The windows show the laundromat as empty even though they are still inside.','They learn the machines are swapping objects between two versions of the same night.','They escape carrying one jacket neither person recognizes.']},
  {genre:'thriller',title:'Tomorrow Called Twice',setting:'apartment',hook:'A phone receives a call from its own number dated tomorrow.',beats:['The caller predicts a blackout.','The next prediction is a hallway camera failure.','Security footage shows the two characters leaving the building tomorrow.','The future voice warns them not about the building, but about copies waiting outside.','Both phones ring from the same number.','Someone knocks using the exact rhythm heard on the call.']},
  {genre:'horror',title:'Room 404 Was My Bedroom',setting:'motel',hook:'A motel room is an exact copy of one character’s childhood bedroom.',beats:['Old photographs include the other character years before they met.','The hallway grows longer each time they leave.','Objects in the room change to match private memories.','They realize the room is testing which memories belong to the person inside.','They force the door open and reach the parking lot.','Room 404 appears reflected in every dark car window.']},
  {genre:'comedy-mystery',title:'The Duck Detective Hired Me',setting:'park',hook:'A duck in a tiny detective hat drops a case file at their feet.',beats:['The file contains photos of their lunch before they bought it.','Pigeons begin following them like surveillance.','The clues lead under a café patio.','They discover a fake snack-smuggling operation.','The duck planted the evidence to keep the investigation alive.','The duck hands them an invoice for solving its own case.']},
  {genre:'thriller',title:'The Bus Stop After the Last Stop',setting:'bus',hook:'A city bus passes the same empty street for the third time.',beats:['The route display changes to the characters’ names.','Each pull of the stop cord makes another passenger disappear.','The driver says only one person can leave.','Every house outside belongs to someone who vanished from the bus.','The bus stops at one character’s childhood home.','A person with the other character’s face is waiting on the porch.']},
  {genre:'horror',title:'Someone Keeps Using My Doorbell Camera',setting:'apartment',hook:'The doorbell app records a visitor who only appears when nobody is home.',beats:['The visitor never faces the camera.','A package arrives containing a photo taken from inside the apartment.','The camera history shows a clip that has not happened yet.','The future clip shows one character opening the door.','They disable the camera, but notifications continue.','The final alert says the visitor is already inside.']},
  {genre:'mystery',title:'The Apartment Across From Mine Is Empty',setting:'apartment',hook:'A supposedly vacant apartment has someone copying their nightly routine.',beats:['The copy turns lights on seconds after they do.','The leasing office says the unit has been empty for years.','A note appears under their door describing tomorrow morning.','They watch the empty unit and see themselves watching back.','The note predicts one person will cross the hall.','The opposite door opens before either of them moves.']},
  {genre:'horror',title:'The Voice in My GPS Knows My Name',setting:'street',hook:'A navigation app starts giving directions using one character’s first name.',beats:['It sends them away from the normal route.','The map shows a road that does not exist.','The voice mentions something private from childhood.','Turning the app off does not stop the directions.','They realize the destination is their current location.','The final instruction tells them not to look in the back seat.']},
  {genre:'comedy-thriller',title:'My Replacement Arrived Early',setting:'office',hook:'An exact copy of one character is already at their desk doing their job.',beats:['Coworkers insist the copy has always worked there.','HR records show both employees have the same ID.','More copies arrive from the elevator.','Each copy remembers a different version of the character’s life.','The first copy claims the original left months ago.','The office badge changes names before anyone can leave.']}
];

function hashSeed(value){let h=2166136261;for(const c of String(value)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
function pick(list,seed,offset=0){return list[((seed+Math.imul(offset+1,2654435761))>>>0)%list.length];}
function wordCount(s){return String(s||'').trim().split(/\s+/).filter(Boolean).length;}
function durationForSeed(seedValue){const m=String(seedValue).match(/^(.*)-slot-(\d+)$/);if(m){const rot=hashSeed(`${m[1]}:duration`)%DAILY_DURATION_MINUTES.length;return DAILY_DURATION_MINUTES[(Math.max(0,Number(m[2])-1)+rot)%DAILY_DURATION_MINUTES.length];}return DAILY_DURATION_MINUTES[hashSeed(`${seedValue}:duration`)%DAILY_DURATION_MINUTES.length];}
function normalize(s){return String(s||'').toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();}
function tokens(s){return new Set(normalize(s).split(' ').filter(w=>w.length>3));}
function similarity(a,b){const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return 0;let both=0;for(const x of A)if(B.has(x))both++;return both/Math.max(A.size,B.size);}
function repeatedOpening(a,b){const x=normalize(a).split(' ').slice(0,4).join(' ');const y=normalize(b).split(' ').slice(0,4).join(' ');return x&&x===y;}
function dialogueIsFresh(line,previous){if(!line||wordCount(line)<4)return false;for(const old of previous){if(normalize(line)===normalize(old))return false;if(similarity(line,old)>0.64)return false;if(repeatedOpening(line,old))return false;}return true;}
function tidyLine(line){let s=String(line||'').replace(/\s+/g,' ').trim();if(wordCount(s)>28)s=s.split(/\s+/).slice(0,28).join(' ');if(!/[.!?]$/.test(s))s+='.';return s;}

const REACTIONS = ['No. That was not there before.','Check the time on it.','Don’t touch it yet.','I’m checking the hallway.','That makes no sense.','Show me exactly what you saw.','Okay, now I’m worried.','I heard it too.','Back up. Give me a second.','That changed while we were looking at it.','We should leave. Now.','Wait. Look at the reflection.','The door just locked.','Call somebody.','No signal. Of course.','I have an idea, but you’re not going to like it.','Then we do it together.','Something is moving outside.','That is definitely our address.','Read the last line again.'];
const OBSERVATIONS = ['The timestamp is one day ahead.','The lights only flicker when we speak.','There are fresh footprints on the floor.','The camera feed is delayed by exactly ten seconds.','The handle is warm.','The screen just changed by itself.','There is another sound behind the wall.','The same number appears on both phones.','That photo was taken from inside this room.','The exit sign is pointing the wrong way.','The clock stopped at the same minute as the message.','Someone erased the last camera clip.','The elevator indicator skipped a floor.','The shadow moved before you did.','The address on this receipt is ours.','That handwriting looks like mine.','The door across the hall is open now.','The map says we are already at the destination.','The reflection is missing one of us.','The last message was sent from this room.'];
const DECISIONS = ['We take the stairs.','Keep the phone recording.','Leave the lights on.','Do not answer it.','I’ll check the door; you watch the camera.','We are not splitting up.','Take a picture before it changes again.','Put the keys in your pocket.','Call the front desk and say nothing else.','We leave everything and go.','Wait for the next notification.','Cover the mirror.','Lock the second door.','Turn the sound off and watch the screen.','Do exactly what the note says for one minute.','If it moves again, we run.','Stay where I can see you.','Do not look behind us yet.','We need proof before we leave.','One more minute, then we’re gone.'];

function fallbackDialogue(premise,beat,index,speaker,other,seed,previous){const choices=[];if(index===0){choices.push(`${other.name}, ${premise.hook}`,'Look at this. Something is wrong here.','I need you to see this before I touch anything.');}else{choices.push(beat,pick(OBSERVATIONS,seed,index),pick(REACTIONS,seed,index),pick(DECISIONS,seed,index),`${other.name}, ${pick(REACTIONS,seed,index+3)}`,`${pick(OBSERVATIONS,seed,index+5)} ${pick(DECISIONS,seed,index+7)}`);}for(let k=0;k<choices.length;k++){const line=tidyLine(choices[(k+(seed%choices.length))%choices.length]);if(dialogueIsFresh(line,previous))return line;}return tidyLine(`${pick(OBSERVATIONS,seed,index+11)} ${pick(DECISIONS,seed,index+13)}`);}

function proceduralStory(seedValue){const seed=hashSeed(seedValue);const pair=CHARACTER_PAIRS[seed%CHARACTER_PAIRS.length].map(x=>({...x}));const premise=pick(PREMISES,seed,2);const targetMinutes=durationForSeed(seedValue);const targetWords=Math.round(targetMinutes*148);const sceneCount=Math.max(16,Math.round(targetWords/18));const scenes=[];const previous=[];for(let i=0;i<sceneCount;i++){const speaker=pair[i%2];const other=pair[(i+1)%2];const progress=i/Math.max(1,sceneCount-1);const beatIndex=Math.min(premise.beats.length-1,Math.floor(progress*premise.beats.length));const beat=premise.beats[beatIndex];let dialogue=fallbackDialogue(premise,beat,i,speaker,other,seed,previous);previous.push(dialogue);if(previous.length>10)previous.shift();scenes.push({speaker:speaker.id,dialogue,setting:SAFE_SETTINGS.includes(premise.setting)?premise.setting:pick(SAFE_SETTINGS,seed,i),action:pick(SAFE_ACTIONS,seed,i),mood:premise.genre.includes('comedy')?'funny':'tense'});}return {title:premise.title,genre:premise.genre,characters:pair,scenes,targetMinutes,targetSeconds:Math.round(targetMinutes*60),sceneCount:scenes.length,spokenWords:scenes.reduce((n,s)=>n+wordCount(s.dialogue),0),durationRange:'2-9 minutes',sourceStyle:'original-reddit-inspired'};}

function sanitizeGenerated(raw,seedValue){if(!raw||!Array.isArray(raw.scenes))return null;const seed=hashSeed(seedValue);const pair=CHARACTER_PAIRS[seed%CHARACTER_PAIRS.length].map(x=>({...x}));const targetMinutes=durationForSeed(seedValue);const desired=Math.max(16,Math.round(targetMinutes*7.2));const out=[];const history=[];for(let i=0;i<raw.scenes.length&&out.length<desired;i++){const s=raw.scenes[i]||{};const line=tidyLine(s.dialogue);if(!dialogueIsFresh(line,history))continue;history.push(line);if(history.length>12)history.shift();out.push({speaker:s.speaker==='B'?'B':'A',dialogue:line,setting:SAFE_SETTINGS.includes(s.setting)?s.setting:pick(SAFE_SETTINGS,seed,i),action:SAFE_ACTIONS.includes(s.action)?s.action:pick(SAFE_ACTIONS,seed,i),mood:s.mood==='funny'?'funny':'tense'});}if(out.length<Math.min(14,desired*0.7))return null;while(out.length<desired){const p=proceduralStory(`${seedValue}:fill:${out.length}`);const candidate=p.scenes[out.length%p.scenes.length];if(dialogueIsFresh(candidate.dialogue,history)){out.push(candidate);history.push(candidate.dialogue);if(history.length>12)history.shift();}else{candidate.dialogue=tidyLine(pick(OBSERVATIONS,seed,out.length)+' '+pick(DECISIONS,seed,out.length+5));out.push(candidate);}}return {title:String(raw.title||'Ruby’s Realm Story').slice(0,80),genre:String(raw.genre||'thriller').slice(0,30),characters:pair,scenes:out,targetMinutes,targetSeconds:Math.round(targetMinutes*60),sceneCount:out.length,spokenWords:out.reduce((n,s)=>n+wordCount(s.dialogue),0),durationRange:'2-9 minutes',sourceStyle:'original-reddit-inspired'};}

async function aiStory(seedValue){const targetMinutes=durationForSeed(seedValue);const targetScenes=Math.max(16,Math.round(targetMinutes*7.2));const premise=pick(PREMISES,hashSeed(seedValue),4);const prompt=`Write an ORIGINAL ${targetMinutes}-minute vertical story loosely inspired by the conversational realism of internet first-person story posts, but do not copy, quote, paraphrase, or adapt any identifiable Reddit post. Premise: ${premise.hook} Genre: ${premise.genre}. Return JSON with title, genre, and scenes. Each scene needs speaker A or B, dialogue, setting, action, mood. Produce about ${targetScenes} scenes. Dialogue must sound like two normal adults speaking plainly under pressure. HARD RULES: no filler, no repeated catchphrases, do not repeatedly say the other person's name, do not restate the same clue, do not start multiple lines the same way, do not use motivational narration, keep each line 5-24 words, every line must add a new fact/reaction/decision/action, alternate observation/reaction/action naturally, build a complete plot with hook, escalation, twist, climax, ending. Allowed settings: ${SAFE_SETTINGS.join(', ')}. Allowed actions: ${SAFE_ACTIONS.join(', ')}.`;const raw=await generateStoryJson(prompt);return sanitizeGenerated(raw,seedValue);}

export async function createStory(seedValue){if(hasGatewayAuth()){try{const story=await aiStory(seedValue);if(story)return story;}catch(e){console.warn('AI story generation failed; using original procedural story',e.message);}}return proceduralStory(seedValue);}

export function previewStory(seedValue){const story=proceduralStory(seedValue);return {title:story.title,genre:story.genre,targetMinutes:story.targetMinutes,targetSeconds:story.targetSeconds,sceneCount:story.sceneCount,spokenWords:story.spokenWords,durationRange:story.durationRange,sourceStyle:story.sourceStyle};}
