import crypto from 'node:crypto';
import fs from 'node:fs';

const REPO=process.env.GITHUB_REPOSITORY||'RubysRealm/RubysRealm';
const TOKEN=process.env.GITHUB_TOKEN;
const KEY_TEXT=process.env.SOCIALBOT_KEY||'';
const STATE_BRANCH='social-bot-state';
const STATE_PATH='social-bot/state.enc';
const STATUS_PATH='social-bot/status.json';
const BLOCKED_HOSTS=['tiktok.com','instagram.com','facebook.com','x.com','twitter.com','youtube.com','reddit.com','snapchat.com','pinterest.com','linkedin.com','threads.net'];
const DEFAULT_STATE={version:1,paused:false,stopped:false,connected:null,identities:[],jobs:[],failures:[],history:[],siteProfile:{},stats:{discovery:0,video:0,profile:0,random:0}};

function b64u(buf){return Buffer.from(buf).toString('base64url')}
function unb64u(s){return Buffer.from(String(s||''),'base64url')}
function getKey(){const k=unb64u(KEY_TEXT);if(k.length!==32)throw new Error('SOCIALBOT_KEY_MISSING_OR_INVALID');return k}
function decryptPacked(packed){const [v,ivs,cts]=String(packed||'').split('.');if(v!=='v1'||!ivs||!cts)throw new Error('BAD_ENCRYPTED_PAYLOAD');const iv=unb64u(ivs),all=unb64u(cts),tag=all.subarray(all.length-16),ct=all.subarray(0,all.length-16);const d=crypto.createDecipheriv('aes-256-gcm',getKey(),iv);d.setAuthTag(tag);return Buffer.concat([d.update(ct),d.final()])}
function encryptPacked(buf){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',getKey(),iv);const ct=Buffer.concat([c.update(buf),c.final()]),tag=c.getAuthTag();return `v1.${b64u(iv)}.${b64u(Buffer.concat([ct,tag]))}`}
function urlHash(url){return b64u(crypto.createHash('sha256').update(new URL(url).origin).digest())}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function now(){return new Date().toISOString()}
function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function choice(a){return a[Math.floor(Math.random()*a.length)]}
function slug(s){return s.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'.').replace(/^\.+|\.+$/g,'').slice(0,38)}
function assertTarget(url,origin=null){const u=new URL(url);if(!['http:','https:'].includes(u.protocol))throw new Error('UNSUPPORTED_URL_PROTOCOL');const h=u.hostname.toLowerCase().replace(/^www\./,'');if(BLOCKED_HOSTS.some(x=>h===x||h.endsWith('.'+x)))throw new Error('PUBLIC_SOCIAL_PLATFORM_BLOCKED');if(origin&&u.origin!==origin)throw new Error('TARGET_MUST_MATCH_CONNECTED_PLATFORM');return u}
function emptyCat(){return{passed:0,failed:0,pending:0,running:0}}

async function api(path,opts={}){if(!TOKEN)throw new Error('GITHUB_TOKEN_MISSING');const r=await fetch(`https://api.github.com/repos/${REPO}${path}`,{...opts,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${TOKEN}`,'X-GitHub-Api-Version':'2022-11-28',...(opts.headers||{})}});if(!r.ok&&r.status!==404){throw new Error(`GITHUB_API_${r.status}:${(await r.text()).slice(0,180)}`)}return r}
async function ensureStateBranch(){let r=await api(`/git/ref/heads/${STATE_BRANCH}`);if(r.status!==404)return;const main=await (await api('/git/ref/heads/main')).json();await api('/git/refs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ref:`refs/heads/${STATE_BRANCH}`,sha:main.object.sha})})}
async function readFileBranch(path){await ensureStateBranch();const r=await api(`/contents/${path}?ref=${STATE_BRANCH}`);if(r.status===404)return null;return await r.json()}
async function writeFileBranch(path,text,message){const prev=await readFileBranch(path);const body={message,content:Buffer.from(text).toString('base64'),branch:STATE_BRANCH};if(prev?.sha)body.sha=prev.sha;const r=await api(`/contents/${path}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error('STATE_WRITE_FAILED')}
async function loadState(){const f=await readFileBranch(STATE_PATH);if(!f)return structuredClone(DEFAULT_STATE);try{return JSON.parse(decryptPacked(Buffer.from(f.content,'base64').toString()).toString())}catch(e){if(String(e.message).includes('STATE'))throw e;throw new Error('STATE_DECRYPT_FAILED')}}
async function saveState(state){state.updatedAt=now();await writeFileBranch(STATE_PATH,encryptPacked(Buffer.from(JSON.stringify(state))),'Social Bot: persist encrypted state')}
function summarize(state,last={}){const c={identities:emptyCat(),accounts:emptyCat(),discovery:emptyCat(),video:emptyCat(),profile:emptyCat(),random:emptyCat()};c.identities.passed=state.identities.length;for(const i of state.identities){if(i.accountStatus==='created')c.accounts.passed++;else if(i.accountStatus==='failed')c.accounts.failed++;else c.accounts.pending++}const map={create_account:'accounts',discovery:'discovery',video:'video',profile_follow:'profile',random_follow:'random'};for(const j of state.jobs){const k=map[j.kind];if(!k)continue;if(j.status==='passed')c[k].passed++;else if(j.status==='failed')c[k].failed++;else if(j.status==='running')c[k].running++;else if(['pending','queued'].includes(j.status))c[k].pending++}const activeNow=state.identities.filter(i=>i.accountStatus==='created'&&i.lastActivityAt&&Date.now()-Date.parse(i.lastActivityAt)<2*3600e3).length;const reasons={};for(const f of state.failures){const k=`${f.kind}|${f.reason}`;reasons[k]=(reasons[k]||0)+1}return{updatedAt:now(),connected:state.connected||{ok:false,message:'Not connected'},worker:{paused:!!state.paused,stopped:!!state.stopped,lastRunOk:last.ok!==false,message:state.paused?'Paused':state.stopped?'Stopped':'Remote worker ready',emailConfigured:!!(process.env.SOCIALBOT_GMAIL_USER&&process.env.SOCIALBOT_GMAIL_APP_PASSWORD)},counts:{identities:state.identities.length,accountsCreated:c.accounts.passed,activeNow,failed:Object.values(c).reduce((n,x)=>n+x.failed,0)},categories:c,failureReasons:Object.entries(reasons).map(([k,count])=>{const [kind,reason]=k.split('|');return{kind,reason,count}}).sort((a,b)=>b.count-a.count),lastRequestId:last.requestId||null,lastRequestStatus:last.status||null,lastMessage:last.message||null}}
async function saveAll(state,last={}){await saveState(state);await writeFileBranch(STATUS_PATH,JSON.stringify(summarize(state,last),null,2),'Social Bot: update aggregate status')}

const firstNames=['Mason','Logan','Ethan','Avery','Noah','Liam','Lucas','Owen','Caleb','Wyatt','Carter','Miles','Parker','Blake','Jordan','Taylor','Morgan','Riley','Harper','Cameron','Aiden','Nolan','Levi','Hudson','Dylan','Cole','Sawyer','Reese','Kai','Evan','Mia','Emma','Olivia','Ava','Ella','Sofia','Chloe','Layla','Nora','Zoe','Lucy','Maya','Stella','Leah','Naomi','Sadie','Claire','Brooke','Paige'];
const lastNames=['Carter','Rivers','Wilson','Collins','Walker','Hayes','Bennett','Parker','Reed','Foster','Morgan','Brooks','Turner','Cooper','Gray','Bailey','Murphy','Price','Ward','Bell','Ross','Kelly','Cook','Wood','Barnes','Powell','Long','Perry','Hughes','Butler','Simmons','Bryant','Griffin','Russell','Diaz','Hayden','Coleman','Jenkins','Morris','Sanders','Fisher','West','Stone','Wells','Lane','Warren','Fox','Mills','Grant','Hart'];
const interests=['gaming','automotive','sports','technology','music','movies','fitness','food','travel','business','photography','outdoors','fashion','DIY','education','comedy','science'];
function uniqueHandle(state,first,last){for(let x=0;x<50;x++){const n=rand(1,9999);const variants=[`${first}${last}${n}`,`${first[0]}${last}${n}`,`${first}.${last}${n}`,`${first}${n}`];const h=slug(choice(variants)).replaceAll('.','');if(!state.identities.some(i=>i.username===h))return h}return `user${crypto.randomUUID().slice(0,8)}`}
function generateIdentity(state){const first=choice(firstNames),last=choice(lastNames),username=uniqueHandle(state,first,last);const gmail=process.env.SOCIALBOT_GMAIL_USER||'';if(!gmail.includes('@'))throw new Error('VERIFICATION_EMAIL_NOT_CONFIGURED');const [local,domain]=gmail.split('@');const suffix=slug(choice([`${first}.${last}${rand(1,999)}`,`${first[0]}${last}${rand(1,999)}`,`${username}`]));const email=`${local}+${suffix}@${domain}`;const year=rand(1980,2004),month=String(rand(1,12)).padStart(2,'0'),day=String(rand(1,28)).padStart(2,'0');return{id:crypto.randomUUID(),first,last,displayName:`${first} ${last}`,username,email,dob:`${year}-${month}-${day}`,password:`Sb!${crypto.randomBytes(9).toString('base64url')}7`,interests:Array.from(new Set([choice(interests),choice(interests),choice(interests)])),createdAt:now(),accountStatus:'not_created',storageState:null,lastActivityAt:null}}
function addFailure(state,kind,reason,job=null,identityId=null){state.failures.push({id:crypto.randomUUID(),kind,reason:String(reason).slice(0,240),jobId:job?.id||null,identityId:identityId||job?.identityId||null,createdAt:now(),attempts:(job?.attempts||0)+1});if(state.failures.length>1000)state.failures=state.failures.slice(-1000)}
function scheduleFor(state,kind,identities,params){const spread=Math.max(0,Number(params.spreadHours||0))*3600e3;const base=Date.now();for(const ident of identities){state.jobs.push({id:crypto.randomUUID(),kind,identityId:ident.id,targetUrl:params.url||null,min:params.min||1,max:params.max||1,status:'pending',dueAt:new Date(base+(spread?Math.floor(Math.random()*spread):0)).toISOString(),attempts:0,createdAt:now()})}}

let chromiumMod=null;
async function browserLaunch(){if(!chromiumMod){chromiumMod=await import('playwright-core')}const candidates=[process.env.CHROME_PATH,'/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/usr/bin/chromium','/usr/bin/chromium-browser'].filter(Boolean);const exe=candidates.find(p=>fs.existsSync(p));if(!exe)throw new Error('CHROME_NOT_FOUND_ON_WORKER');return chromiumMod.chromium.launch({headless:true,executablePath:exe,args:['--no-sandbox','--disable-dev-shm-usage']})}
async function scanPage(page){const data=await page.evaluate(()=>{const norm=e=>({tag:e.tagName.toLowerCase(),type:e.getAttribute('type')||'',name:e.getAttribute('name')||'',id:e.id||'',placeholder:e.getAttribute('placeholder')||'',aria:e.getAttribute('aria-label')||'',text:(e.innerText||e.value||'').trim().slice(0,100)});return{title:document.title,url:location.href,inputs:[...document.querySelectorAll('input,select,textarea')].slice(0,80).map(norm),buttons:[...document.querySelectorAll('button,[role=button],input[type=submit]')].slice(0,80).map(norm),links:[...document.querySelectorAll('a')].slice(0,120).map(a=>({text:(a.innerText||a.getAttribute('aria-label')||'').trim().slice(0,100),href:a.href}))}});return data}
async function clickText(page,re,required=false){const candidates=[page.getByRole('button',{name:re}),page.getByRole('link',{name:re}),page.getByText(re,{exact:false})];for(const loc of candidates){try{if(await loc.first().isVisible({timeout:800})){await loc.first().click({timeout:4000});await page.waitForTimeout(400);return true}}catch{}}if(required)throw new Error(`CONTROL_NOT_FOUND:${re}`);return false}
async function fillBest(page,kind,value){const patterns={email:/email|e-mail/i,password:/password|passcode/i,username:/user\s*name|username|handle/i,name:/display\s*name|full\s*name|name/i,dob:/birth|birthday|date of birth|dob/i,code:/verification|verify|otp|security code|code/i};const re=patterns[kind];let selectors=[];if(kind==='email')selectors.push('input[type=email]');if(kind==='password')selectors.push('input[type=password]');if(kind==='dob')selectors.push('input[type=date]');selectors.push('input,textarea');for(const sel of selectors){const loc=page.locator(sel);for(let i=0;i<Math.min(await loc.count(),30);i++){const el=loc.nth(i);try{if(!(await el.isVisible()))continue;const meta=await el.evaluate(e=>[e.name,e.id,e.placeholder,e.getAttribute('aria-label'),e.autocomplete].filter(Boolean).join(' '));if(sel!=='input,textarea'||re.test(meta)){await el.fill(String(value));return true}}catch{}}}return false}
async function enterDob(page,dob){if(await fillBest(page,'dob',dob))return true;const [y,m,d]=dob.split('-');const selects=page.locator('select');if(await selects.count()>=3){try{for(let i=0;i<Math.min(3,await selects.count());i++){const s=selects.nth(i);const txt=((await s.getAttribute('name'))||'')+' '+((await s.getAttribute('aria-label'))||'');if(/month/i.test(txt))await s.selectOption(String(Number(m)));else if(/day/i.test(txt))await s.selectOption(String(Number(d)));else if(/year/i.test(txt))await s.selectOption(y)}return true}catch{}}return false}
async function gotoSignup(page,base){await page.goto(base,{waitUntil:'domcontentloaded',timeout:35000});await page.waitForTimeout(500);if(await clickText(page,/sign\s*up|create\s*(an\s*)?account|register|join/i,false))await page.waitForTimeout(700)}
async function waitForVerification(alias,afterMs){const user=process.env.SOCIALBOT_GMAIL_USER,pass=process.env.SOCIALBOT_GMAIL_APP_PASSWORD;if(!user||!pass)throw new Error('GMAIL_VERIFICATION_NOT_CONFIGURED');const {ImapFlow}=await import('imapflow');const client=new ImapFlow({host:'imap.gmail.com',port:993,secure:true,auth:{user,pass},logger:false});await client.connect();try{for(let attempt=0;attempt<24;attempt++){let lock=await client.getMailboxLock('INBOX');try{const uids=await client.search({to:alias,since:new Date(afterMs-120000)},{uid:true});if(uids.length){const uid=uids[uids.length-1];const msg=await client.fetchOne(uid,{source:true,envelope:true},{uid:true});const text=msg.source?.toString()||'';const code=text.match(/(?:code|verification|verify|otp)[^0-9]{0,80}([0-9]{4,8})/i)?.[1]||text.match(/\b([0-9]{6})\b/)?.[1];const link=text.match(/https?:\/\/[^\s"'<>]+/i)?.[0]?.replace(/&amp;/g,'&');if(code||link)return{code,link,uid}}}finally{lock.release()}await sleep(5000)}throw new Error('VERIFICATION_EMAIL_TIMEOUT')}finally{await client.logout().catch(()=>{})}}
async function completeSignup(state,ident){const base=state.connected?.origin;if(!base)throw new Error('SITE_NOT_CONNECTED');const browser=await browserLaunch();const ctx=await browser.newContext();const page=await ctx.newPage();try{await gotoSignup(page,base);await enterDob(page,ident.dob).catch(()=>false);let emailDone=await fillBest(page,'email',ident.email);if(!emailDone){await clickText(page,/use (phone or )?email|email/i,false);emailDone=await fillBest(page,'email',ident.email)}if(!emailDone)throw new Error('EMAIL_FIELD_NOT_FOUND');const requested=Date.now();await clickText(page,/next|continue|send code|verify|submit|sign\s*up|create/i,true);await page.waitForTimeout(900);const codeField=await fillBest(page,'code','');if(codeField){const v=await waitForVerification(ident.email,requested);if(v.code){await fillBest(page,'code',v.code);await clickText(page,/next|continue|verify|submit/i,true)}else if(v.link){await page.goto(v.link,{waitUntil:'domcontentloaded',timeout:35000})}await page.waitForTimeout(700)}await fillBest(page,'password',ident.password).catch(()=>false);await fillBest(page,'username',ident.username).catch(()=>false);await fillBest(page,'name',ident.displayName).catch(()=>false);for(let i=0;i<3;i++){const did=await clickText(page,/next|continue|submit|create|sign\s*up|finish|done/i,false);if(!did)break;await page.waitForTimeout(700)}if(/captcha|security challenge|unusual activity/i.test((await page.locator('body').innerText()).slice(0,8000)))throw new Error('SECURITY_CHALLENGE_BLOCKED');const st=await ctx.storageState();return{storageState:st,url:page.url()}}finally{await ctx.close().catch(()=>{});await browser.close().catch(()=>{})}}
async function contextForIdentity(ident){const browser=await browserLaunch();const ctx=await browser.newContext(ident.storageState?{storageState:ident.storageState}:{});return{browser,ctx,page:await ctx.newPage()}}
async function performJob(state,job){const ident=state.identities.find(i=>i.id===job.identityId);if(!ident)throw new Error('IDENTITY_NOT_FOUND');if(job.kind!=='create_account'&&ident.accountStatus!=='created')throw new Error('ACCOUNT_NOT_CREATED');const origin=state.connected.origin;if(job.kind==='create_account'){const out=await completeSignup(state,ident);ident.storageState=out.storageState;ident.accountStatus='created';ident.accountCreatedAt=now();return}
const {browser,ctx,page}=await contextForIdentity(ident);try{if(job.kind==='discovery'){await page.goto(origin,{waitUntil:'domcontentloaded',timeout:35000});for(let i=0;i<rand(2,6);i++){await page.mouse.wheel(0,rand(300,1000));await page.waitForTimeout(rand(500,1600));if(Math.random()<.35)await clickText(page,/like|heart/i,false)}state.stats.discovery++;}
else if(job.kind==='video'){assertTarget(job.targetUrl,origin);await page.goto(job.targetUrl,{waitUntil:'domcontentloaded',timeout:35000});await page.waitForTimeout(rand(1000,2500));await clickText(page,/like|heart/i,false);state.stats.video++;}
else if(job.kind==='profile_follow'){assertTarget(job.targetUrl,origin);await page.goto(job.targetUrl,{waitUntil:'domcontentloaded',timeout:35000});await clickText(page,/^follow$|follow\s*user/i,true);state.stats.profile++;}
else if(job.kind==='random_follow'){await page.goto(origin,{waitUntil:'domcontentloaded',timeout:35000});const links=await page.locator('a').evaluateAll((els,origin)=>els.map(a=>a.href).filter(h=>h&&h.startsWith(origin)&&(/\/@|\/profile|\/user\//i.test(h))),origin);const unique=[...new Set(links)];if(!unique.length)throw new Error('NO_PROFILE_LINKS_DISCOVERED');const count=rand(job.min||1,job.max||3);for(const target of unique.sort(()=>Math.random()-.5).slice(0,count)){await page.goto(target,{waitUntil:'domcontentloaded',timeout:35000});await clickText(page,/^follow$|follow\s*user/i,false);await page.waitForTimeout(rand(400,1200));state.stats.random++;}}
ident.storageState=await ctx.storageState();ident.lastActivityAt=now();}finally{await ctx.close().catch(()=>{});await browser.close().catch(()=>{})}}

async function connectSite(state,cmd){const u=assertTarget(cmd.platformUrl);const browser=await browserLaunch();const ctx=await browser.newContext();const page=await ctx.newPage();try{await page.goto(u.origin,{waitUntil:'domcontentloaded',timeout:35000});const home=await scanPage(page);let signup=null;try{if(await clickText(page,/sign\s*up|create\s*(an\s*)?account|register|join/i,false)){await page.waitForTimeout(600);signup=await scanPage(page)}}catch{}const inputText=(signup||home).inputs.map(x=>[x.type,x.name,x.id,x.placeholder,x.aria].join(' ')).join(' ');state.connected={ok:true,origin:u.origin,urlHash:urlHash(u.origin),message:'Connected and mapped',scanSummary:`Home: ${home.inputs.length} inputs · ${home.buttons.length} buttons · ${home.links.length} links${signup?` · Signup: ${signup.inputs.length} inputs`:''}`,scannedAt:now()};state.siteProfile={home:{title:home.title,counts:{inputs:home.inputs.length,buttons:home.buttons.length,links:home.links.length}},signupDetected:!!signup,emailField:/email/i.test(inputText),passwordField:/password/i.test(inputText),codeField:/code|otp|verification/i.test(inputText)};state.stopped=false;return state.connected}finally{await ctx.close().catch(()=>{});await browser.close().catch(()=>{})}}
async function processDue(state,limit=12){if(state.paused||state.stopped)return 0;const due=state.jobs.filter(j=>j.status==='pending'&&Date.parse(j.dueAt)<=Date.now()).sort((a,b)=>Date.parse(a.dueAt)-Date.parse(b.dueAt)).slice(0,limit);for(const job of due){job.status='running';job.startedAt=now();try{await performJob(state,job);job.status='passed';job.finishedAt=now()}catch(e){job.attempts=(job.attempts||0)+1;job.status='failed';job.reason=String(e.message||e);job.finishedAt=now();const ident=state.identities.find(i=>i.id===job.identityId);if(job.kind==='create_account'&&ident)ident.accountStatus='failed';addFailure(state,job.kind,job.reason,job)}}return due.length}
function pickEligible(state,count,createdOnly=false){let arr=state.identities.filter(i=>createdOnly?i.accountStatus==='created':i.accountStatus!=='created');return arr.sort(()=>Math.random()-.5).slice(0,count)}
async function handleCommand(state,cmd){assertTarget(cmd.platformUrl);const kind=cmd.kind,p=cmd.params||{};if(kind==='connect'){await connectSite(state,cmd);return'Connected'}if(!state.connected?.ok||state.connected.origin!==new URL(cmd.platformUrl).origin)throw new Error('CONNECT_SITE_FIRST');if(kind==='generate'){const amount=Math.min(5000,Math.max(1,Number(p.amount||1)));for(let i=0;i<amount;i++)state.identities.push(generateIdentity(state));return`Generated ${amount} identities`}
if(kind==='create_accounts'){const ids=state.identities.filter(i=>i.accountStatus==='not_created'||i.accountStatus==='failed').slice(0,Math.max(1,Number(p.amount||1)));for(const i of ids)i.accountStatus='queued';scheduleFor(state,'create_account',ids,p);return`Queued ${ids.length} account signups`}
if(kind==='discovery'){const ids=pickEligible(state,Number(p.amount||1),true);scheduleFor(state,'discovery',ids,p);return`Queued ${ids.length} discovery sessions`}
if(kind==='video'){assertTarget(p.url,state.connected.origin);const ids=pickEligible(state,Number(p.amount||1),true);scheduleFor(state,'video',ids,p);return`Queued ${ids.length} video interactions`}
if(kind==='profile_follow'){assertTarget(p.url,state.connected.origin);const ids=pickEligible(state,Number(p.amount||1),true);scheduleFor(state,'profile_follow',ids,p);return`Queued ${ids.length} profile follows`}
if(kind==='random_follow'){const ids=pickEligible(state,Number(p.amount||1),true);scheduleFor(state,'random_follow',ids,p);return`Queued ${ids.length} random-follow sessions`}
if(kind==='fix_failed'){const category=p.category||'all';const aliases={accounts:'create_account',discovery:'discovery',video:'video',profile:'profile_follow',random:'random_follow'};const allowed=category==='all'?null:aliases[category];const failed=state.jobs.filter(j=>j.status==='failed'&&(!allowed||j.kind===allowed));for(const j of failed){j.status='pending';j.reason=null;j.dueAt=now();if(j.kind==='create_account'){const i=state.identities.find(x=>x.id===j.identityId);if(i)i.accountStatus='queued'}}state.failures=state.failures.filter(f=>!failed.some(j=>j.id===f.jobId));return`Requeued ${failed.length} failed tasks`}
if(kind==='pause'){state.paused=true;return'Paused'}if(kind==='resume'){state.paused=false;state.stopped=false;return'Resumed'}if(kind==='stop'){state.stopped=true;for(const j of state.jobs)if(j.status==='pending')j.status='cancelled';return'Stopped and cancelled pending jobs'}throw new Error('UNKNOWN_COMMAND')}

async function main(){let state=await loadState();let last={ok:true,status:'passed',message:'Scheduled check'};try{if(process.argv.includes('--scheduled')){const n=await processDue(state,12);last.message=n?`Processed ${n} due tasks`:'No due tasks'}else{const packed=process.env.SOCIALBOT_PAYLOAD;if(!packed)throw new Error('PAYLOAD_MISSING');const cmd=JSON.parse(decryptPacked(packed).toString());last.requestId=cmd.requestId;last.message=await handleCommand(state,cmd);last.status=['create_accounts','discovery','video','profile_follow','random_follow'].includes(cmd.kind)?'queued':'passed';if(['connect'].includes(cmd.kind)){}else if(!state.paused&&!state.stopped)await processDue(state,4)}state.history.push({at:now(),message:last.message});if(state.history.length>200)state.history=state.history.slice(-200)}catch(e){last.ok=false;last.status='failed';last.message=String(e.message||e);console.error(last.message)}finally{await saveAll(state,last)}if(!last.ok)process.exitCode=1}
main().catch(e=>{console.error(e);process.exit(1)});
