#!/usr/bin/env python3
import datetime as dt
import json
import os
from pathlib import Path

DIR = Path(__file__).resolve().parent
QUEUE_PATH = DIR / "discovery_queue.json"
STATE_PATH = DIR / "state.json"
QUEUE_SIZE = int(os.getenv("FB_DISCOVERY_QUEUE_SIZE", "40"))

# Sourced media only — nothing here is generated by this pipeline.
# These are public-domain AI-generated videos hosted on Wikimedia Commons.
# The list is intentionally restricted to non-advertising/non-brand content.
COMMONS_SOURCES = [
    {
        "provider": "wikimedia-commons",
        "provider_id": "Victoria-crowned-pigeon.webm",
        "key": "commons:Victoria-crowned-pigeon.webm",
        "title_hint": "AI bird",
        "niche": "ai",
        "style": "brainrot-ai-bird",
        "viral_signal": "brainrot-style-sourced",
        "score": 3000,
        "source_url": "https://commons.wikimedia.org/wiki/File:Victoria-crowned-pigeon.webm",
        "download_url": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Victoria-crowned-pigeon.webm",
        "license_kind": "public-domain",
        "license_url": "https://commons.wikimedia.org/wiki/File:Victoria-crowned-pigeon.webm",
        "rights": "Public domain (PD-algorithm on Wikimedia Commons)",
        "creator": "AI-generated source hosted on Wikimedia Commons",
        "duration_hint": 40.0,
    },
    {
        "provider": "wikimedia-commons",
        "provider_id": "Octopus-and-crab.webm",
        "key": "commons:Octopus-and-crab.webm",
        "title_hint": "AI animals",
        "niche": "ai",
        "style": "brainrot-ai-animals",
        "viral_signal": "brainrot-style-sourced",
        "score": 2900,
        "source_url": "https://commons.wikimedia.org/wiki/File:Octopus-and-crab.webm",
        "download_url": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Octopus-and-crab.webm",
        "license_kind": "public-domain",
        "license_url": "https://commons.wikimedia.org/wiki/File:Octopus-and-crab.webm",
        "rights": "Public domain (PD-algorithm on Wikimedia Commons)",
        "creator": "AI-generated source hosted on Wikimedia Commons",
        "duration_hint": 17.0,
    },
    {
        "provider": "wikimedia-commons",
        "provider_id": "Origami-undersea.webm",
        "key": "commons:Origami-undersea.webm",
        "title_hint": "Surreal AI animals",
        "niche": "ai",
        "style": "brainrot-ai-surreal",
        "viral_signal": "brainrot-style-sourced",
        "score": 2800,
        "source_url": "https://commons.wikimedia.org/wiki/File:Origami-undersea.webm",
        "download_url": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Origami-undersea.webm",
        "license_kind": "public-domain",
        "license_url": "https://commons.wikimedia.org/wiki/File:Origami-undersea.webm",
        "rights": "Public domain (PD-algorithm on Wikimedia Commons)",
        "creator": "AI-generated source hosted on Wikimedia Commons",
        "duration_hint": 20.0,
    },
]


def load_state():
    if not STATE_PATH.exists():
        return {"current": None, "completed": []}
    try:
        state = json.loads(STATE_PATH.read_text())
    except Exception:
        return {"current": None, "completed": []}
    state.setdefault("current", None)
    state.setdefault("completed", [])
    return state


def build_queue():
    state = load_state()
    completed = {str(x) for x in state.get("completed") or []}
    current = state.get("current") or {}
    current_key = str((current.get("candidate") or {}).get("key") or "")

    candidates = [
        dict(item) for item in COMMONS_SOURCES
        if item["key"] not in completed and item["key"] != current_key
    ][:QUEUE_SIZE]

    payload = {
        "generatedAt": dt.datetime.now(dt.timezone.utc).isoformat(),
        "contentFocus": ["sourced-ai-brainrot", "ai-birds", "surreal-ai-animals"],
        "sourceMode": "sourced-only",
        "rejectAdsBrands": True,
        "candidates": candidates,
    }
    QUEUE_PATH.write_text(json.dumps(payload, indent=2) + "\n")
    print(json.dumps({"queued": len(candidates), "top": candidates[:3]}, indent=2))
    if not candidates:
        raise RuntimeError("No unused sourced AI brainrot-style candidates are currently available.")


if __name__ == "__main__":
    build_queue()
