const http=require('http'),fs=require('fs'),path=require('path'),URL=require('url').URL;
const PORT=process.env.PORT||10000,K1='https://external-api.kalshi.com/trade-api/v2',K2='https://api.elections.kalshi.com/trade-api/v2',CB='https://api.exchange.coinbase.com',CBAPP='https://api.coinbase.com',KR='https://api.kraken.com/0/public';
const H={'User-Agent':'ChatGPT-Kalshi-BTC15-Test/1.0 analytics-only','Accept':'application/json'};
let liveCbPrice=null,liveCbBid=null,liveCbAsk=null,liveCbTime=0,cbWs=null,liveAppSpot=null,liveAppSpotTime=0,liveAppRef=null,liveAppRefTime=0;const brtiBook={},BRTI_W={Coinbase:3800,Kraken:900,Bitstamp:600,Gemini:50};let brtiProxy=null,brtiProxyTime=0,brtiSpread=null;function setBrtiQuote(v,b,a){b=Number(b);a=Number(a);if(!Number.isFinite(b)||!Number.isFinite(a)||a<=b)return;brtiBook[v]={bid:b,ask:a,ts:Date.now()};calcBrti()}function calcBrti(){let n=0,d=0,m=[];const now=Date.now();for(const v of Object.keys(BRTI_W)){const q=brtiBook[v];if(!q||now-q.ts>5000)continue;const mid=(q.bid+q.ask)/2,w=BRTI_W[v];n+=mid*w;d+=w;m.push(mid)}if(d>0){brtiProxy=n/d;brtiProxyTime=now;brtiSpread=m.length>1?Math.max(...m)-Math.min(...m):0;pushPrice()}}const priceClients=new Set();function pushPrice(){const proxyFresh=Number.isFinite(brtiProxy)&&(Date.now()-brtiProxyTime<5000),refFresh=Number.isFinite(liveAppRef)&&(Date.now()-liveAppRefTime<5000),spotFresh=Number.isFinite(liveAppSpot)&&(Date.now()-liveAppSpotTime<5000),p=proxyFresh?brtiProxy:(refFresh?liveAppRef:(spotFresh?liveAppSpot:liveCbPrice)),t=proxyFresh?brtiProxyTime:(refFresh?liveAppRefTime:(spotFresh?liveAppSpotTime:liveCbTime));if(!Number.isFinite(p))return;const msg='data: '+JSON.stringify({price:p,time:t,source:proxyFresh?'brti-proxy':(refFresh?'coinbase-app-reference':(spotFresh?'coinbase-app-spot':'coinbase-exchange-fallback')),brti_proxy:brtiProxy,brti_spread:brtiSpread,reference_price:liveAppRef,spot_price:liveAppSpot,exchange_price:liveCbPrice,venues:Object.keys(brtiBook).filter(v=>Date.now()-brtiBook[v].ts<5000)})+'\n\n';for(const r of priceClients){try{r.write(msg)}catch(e){priceClients.delete(r)}}}
function connectCoinbaseWs(){try{if(cbWs){try{cbWs.close()}catch(e){}}cbWs=new WebSocket('wss://ws-feed.exchange.coinbase.com');cbWs.onopen=()=>cbWs.send(JSON.stringify({type:'subscribe',product_ids:['BTC-USD'],channels:['ticker']}));cbWs.onmessage=(ev)=>{try{const m=JSON.parse(ev.data);if(m.type==='ticker'&&m.product_id==='BTC-USD'){const p=Number(m.price),b=Number(m.best_bid),a=Number(m.best_ask);if(Number.isFinite(p)){liveCbPrice=p;liveCbTime=Date.now()}if(Number.isFinite(b))liveCbBid=b;if(Number.isFinite(a))liveCbAsk=a;if(Number.isFinite(b)&&Number.isFinite(a))setBrtiQuote('Coinbase',b,a);if(Number.isFinite(p))pushPrice()}}catch(e){}};cbWs.onclose=()=>setTimeout(connectCoinbaseWs,1000);cbWs.onerror=()=>{try{cbWs.close()}catch(e){}}}catch(e){setTimeout(connectCoinbaseWs,1500)}}
connectCoinbaseWs();
function connectKrakenWs(){try{const ws=new WebSocket('wss://ws.kraken.com');ws.onopen=()=>ws.send(JSON.stringify({event:'subscribe',pair:['XBT/USD'],subscription:{name:'ticker'}}));ws.onmessage=e=>{try{const m=JSON.parse(e.data);if(Array.isArray(m)&&m[1]&&m[1].b&&m[1].a)setBrtiQuote('Kraken',m[1].b[0],m[1].a[0])}catch(x){}};ws.onclose=()=>setTimeout(connectKrakenWs,1200);ws.onerror=()=>{try{ws.close()}catch(x){}}}catch(e){setTimeout(connectKrakenWs,1500)}}
function connectBitstampWs(){try{const ws=new WebSocket('wss://ws.bitstamp.net');ws.onopen=()=>ws.send(JSON.stringify({event:'bts:subscribe',data:{channel:'order_book_btcusd'}}));ws.onmessage=e=>{try{const m=JSON.parse(e.data),d=m&&m.data;if(m.event==='data'&&d&&d.bids&&d.bids.length&&d.asks&&d.asks.length)setBrtiQuote('Bitstamp',d.bids[0][0],d.asks[0][0])}catch(x){}};ws.onclose=()=>setTimeout(connectBitstampWs,1200);ws.onerror=()=>{try{ws.close()}catch(x){}}}catch(e){setTimeout(connectBitstampWs,1500)}}
function connectGeminiWs(){try{const ws=new WebSocket('wss://api.gemini.com/v2/marketdata');let bid=null,ask=null;ws.onopen=()=>ws.send(JSON.stringify({type:'subscribe',subscriptions:[{name:'l2',symbols:['BTCUSD']}]}));ws.onmessage=e=>{try{const m=JSON.parse(e.data);for(const ch of (m.changes||[])){const side=ch[0],px=Number(ch[1]),sz=Number(ch[2]);if(!sz)continue;if(side==='buy')bid=bid===null?px:Math.max(bid,px);if(side==='sell')ask=ask===null?px:Math.min(ask,px)}if(Number.isFinite(bid)&&Number.isFinite(ask)&&ask>bid)setBrtiQuote('Gemini',bid,ask)}catch(x){}};ws.onclose=()=>setTimeout(connectGeminiWs,1200);ws.onerror=()=>{try{ws.close()}catch(x){}}}catch(e){setTimeout(connectGeminiWs,1500)}}
connectKrakenWs();connectBitstampWs();connectGeminiWs();
async function pollCoinbaseAppSpot(){try{const j=await gj(CBAPP+'/v2/prices/BTC-USD/spot'),p=num(j&&j.data&&j.data.amount,null);if(p!==null){liveAppSpot=p;liveAppSpotTime=Date.now();pushPrice()}}catch(e){}finally{setTimeout(pollCoinbaseAppSpot,1000)}}
async function pollCoinbaseAppRef(){try{const j=await gj(CBAPP+'/v2/exchange-rates?currency=BTC'),p=num(j&&j.data&&j.data.rates&&j.data.rates.USD,null);if(p!==null){liveAppRef=p;liveAppRefTime=Date.now();pushPrice()}}catch(e){}finally{setTimeout(pollCoinbaseAppRef,1000)}}
setTimeout(pollCoinbaseAppSpot,50);setTimeout(pollCoinbaseAppRef,100);
let researchScore=0,researchUpdated=0,researchHeadlines=[];
function decodeXml(s){return String(s||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>')}
async function pollInternetResearch(){
  try{
    const u='https://news.google.com/rss/search?q=bitcoin%20OR%20BTC%20when%3A1h&hl=en-US&gl=US&ceid=US%3Aen',r=await fetch(u,{headers:H}),txt=await r.text(),items=[...txt.matchAll(/<item>[\s\S]*?<title>([\s\S]*?)<\/title>[\s\S]*?<pubDate>([\s\S]*?)<\/pubDate>[\s\S]*?<\/item>/gi)].slice(0,25);
    const pos=/\b(rally|surge|approval|approved|inflow|breakout|record|adoption|buying|bullish|gain|gains|rise|rises|soar|soars|upgrade)\b/i;
    const neg=/\b(hack|exploit|ban|crash|liquidation|selloff|outflow|fraud|attack|bearish|lawsuit|drop|drops|plunge|plunges|downgrade)\b/i;
    let s=0,n=0,h=[];
    for(const it of items){const title=decodeXml(it[1]);if(!title)continue;let z=0;if(pos.test(title))z++;if(neg.test(title))z--;s+=z;n++;h.push(title)}
    researchScore=n?clamp(s/Math.sqrt(n),-2,2):0;researchUpdated=Date.now();researchHeadlines=h.slice(0,8);
  }catch(e){researchScore=0}
  finally{setTimeout(pollInternetResearch,60000)}
}
setTimeout(pollInternetResearch,1000);
const num=(v,d=null)=>{const x=Number(v);return v===null||v===undefined||v===''||!Number.isFinite(x)?d:x};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
const std=a=>{if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))};
const ema=(a,p)=>{if(!a.length)return 0;let e=a[0],q=2/(p+1);for(let i=1;i<a.length;i++)e=q*a[i]+(1-q)*e;return e};
const ret=(a,n)=>a.length>n&&a[a.length-1-n]?a[a.length-1]/a[a.length-1-n]-1:0;
const mid=(b,a)=>Number.isFinite(b)&&Number.isFinite(a)?(b+a)/2:Number.isFinite(b)?b:Number.isFinite(a)?a:null;
async function gj(u){const c=new AbortController(),t=setTimeout(()=>c.abort(),7000);try{const r=await fetch(u,{headers:H,signal:c.signal});if(!r.ok)throw Error(r.status+' '+r.statusText);return await r.json()}finally{clearTimeout(t)}}
async function kj(p){try{return await gj(K1+p)}catch(e){return await gj(K2+p)}}
async function kalshiAt(base,p){return await gj(base+p)}
async function strictVerifyTicker(ticker){
  const p='/markets/'+encodeURIComponent(ticker);
  let a=null,b=null,ea=null,eb=null;
  try{a=await kalshiAt(K1,p)}catch(e){ea=e.message||String(e)}
  try{b=await kalshiAt(K2,p)}catch(e){eb=e.message||String(e)}
  const ma=a&&pm(a.market||a),mb=b&&pm(b.market||b);
  if(!ma||!mb)return{ok:false,verified:false,state:'VERIFYING',reason:'Both Kalshi verification endpoints are required',errors:{primary:ea,secondary:eb}};
  const sameTicker=ma.contract_id===ticker&&mb.contract_id===ticker;
  const finalized=ma.status==='finalized'&&mb.status==='finalized';
  const validResult=(ma.result==='yes'||ma.result==='no')&&(mb.result==='yes'||mb.result==='no');
  const sameResult=validResult&&ma.result===mb.result;
  const av=Number(ma.expiration_value),bv=Number(mb.expiration_value),ap=Number(ma.price_to_beat),bp=Number(mb.price_to_beat);
  const valuesPresent=[av,bv,ap,bp].every(Number.isFinite);
  const sameValue=valuesPresent&&Math.abs(av-bv)<0.005;
  const samePtb=valuesPresent&&Math.abs(ap-bp)<0.005;
  const settlementPresent=!!ma.settlement_ts&&!!mb.settlement_ts;
  if(!finalized||!validResult)return{ok:true,verified:false,state:'VERIFYING',reason:'Market is not finalized with an official result on both Kalshi endpoints',market:ma};
  const actualByResult=ma.result==='yes'?'OVER':'UNDER';
  const actualByMath=av>=ap?'OVER':'UNDER';
  const mathAgrees=actualByResult===actualByMath;
  const verified=sameTicker&&sameResult&&sameValue&&samePtb&&settlementPresent&&mathAgrees;
  return{
    ok:true,verified,state:verified?'VERIFIED':'CONFLICT',
    reason:verified?'Dual Kalshi final result and official settlement value agree with PTB math':'Verification sources disagree or settlement math conflicts',
    actual:verified?actualByResult:null,
    settlement_value:valuesPresent?av:null,
    price_to_beat:valuesPresent?ap:null,
    settlement_ts:ma.settlement_ts||null,
    result:ma.result||null,
    checks:{same_ticker:sameTicker,finalized,valid_result:validResult,same_result:sameResult,values_present:valuesPresent,same_settlement_value:sameValue,same_ptb:samePtb,settlement_timestamp_present:settlementPresent,math_agrees:mathAgrees},
    primary:ma,secondary:mb
  }
}
function pm(m){const close=new Date(m.close_time||m.expected_expiration_time||m.expiration_time||0);let open=new Date(m.open_time||close.getTime()-900000);if(!Number.isFinite(open.getTime()))open=new Date(close.getTime()-900000);let ptb=num(m.floor_strike,null);if(ptb===null)ptb=num(m.functional_strike,null);const lg=v=>{const x=num(v,null);return x===null?null:(x>1?x/100:x)};let yb=num(m.yes_bid_dollars,null),ya=num(m.yes_ask_dollars,null),nb=num(m.no_bid_dollars,null),na=num(m.no_ask_dollars,null);if(yb===null)yb=lg(m.yes_bid);if(ya===null)ya=lg(m.yes_ask);if(nb===null)nb=lg(m.no_bid);if(na===null)na=lg(m.no_ask);if(nb===null&&ya!==null)nb=1-ya;if(na===null&&yb!==null)na=1-yb;return{contract_id:String(m.ticker||''),start_utc:open.toISOString(),end_utc:close.toISOString(),price_to_beat:ptb,yes_bid:yb,yes_ask:ya,no_bid:nb,no_ask:na,yes_mid:mid(yb,ya),no_mid:mid(nb,na),result:String(m.result||'').toLowerCase(),status:String(m.status||'').toLowerCase(),expiration_value:num(m.expiration_value,null),settlement_ts:m.settlement_ts||null,strike_type:String(m.strike_type||'')}}
let marketCache=null,marketCacheAt=0;async function market(){if(marketCache&&Date.now()-marketCacheAt<600)return marketCache;const p=await kj('/markets?series_ticker=KXBTC15M&status=open&limit=200'),now=Date.now(),a=[];for(const m of(p.markets||[])){if(!String(m.ticker||'').startsWith('KXBTC15M-'))continue;const x=pm(m),o=Date.parse(x.start_utc),c=Date.parse(x.end_utc),left=(c-now)/1000;if(Number.isFinite(c)&&o<=now+30000&&left>=-15&&left<=960)a.push(x)}a.sort((x,y)=>Date.parse(x.end_utc)-Date.parse(y.end_utc));if(!a.length)throw Error('No active KXBTC15M market found');marketCache=a[0];marketCacheAt=Date.now();return marketCache}
async function spot(){const[ref,app,t,c,b,tr,k]=await Promise.all([gj(CBAPP+'/v2/exchange-rates?currency=BTC').catch(()=>null),gj(CBAPP+'/v2/prices/BTC-USD/spot').catch(()=>null),gj(CB+'/products/BTC-USD/ticker').catch(()=>null),gj(CB+'/products/BTC-USD/candles?granularity=60'),gj(CB+'/products/BTC-USD/book?level=2').catch(()=>null),gj(CB+'/products/BTC-USD/trades?limit=100').catch(()=>null),gj(KR+'/Ticker?pair=XBTUSD').catch(()=>null)]);const refNow=num(ref&&ref.data&&ref.data.rates&&ref.data.rates.USD,null),appNow=num(app&&app.data&&app.data.amount,null),proxyFresh=Number.isFinite(brtiProxy)&&(Date.now()-brtiProxyTime<5000),refFresh=Number.isFinite(liveAppRef)&&(Date.now()-liveAppRefTime<5000),appFresh=Number.isFinite(liveAppSpot)&&(Date.now()-liveAppSpotTime<5000),wsFresh=Number.isFinite(liveCbPrice)&&(Date.now()-liveCbTime<5000),exchangePrice=wsFresh?liveCbPrice:num(t&&t.price,null),price=proxyFresh?brtiProxy:(refNow!==null?refNow:(refFresh?liveAppRef:(appNow!==null?appNow:(appFresh?liveAppSpot:exchangePrice))));if(price===null)throw Error('BTC reference price unavailable');const candles=(Array.isArray(c)?c:[]).filter(x=>Array.isArray(x)&&x.length>=6).map(x=>({low:+x[1],high:+x[2],open:+x[3],close:+x[4],volume:+x[5]})).reverse();let bi=null;if(b){let bs=0,as=0;for(const x of(b.bids||[]).slice(0,25))bs+=+x[1]||0;for(const x of(b.asks||[]).slice(0,25))as+=+x[1]||0;if(bs+as)bi=(bs-as)/(bs+as)}let fi=null;if(Array.isArray(tr)){let buy=0,sell=0;for(const x of tr){const z=+x.size||0;if(x.side==='sell')buy+=z;else if(x.side==='buy')sell+=z}if(buy+sell)fi=(buy-sell)/(buy+sell)}let kp=null;try{const r=k&&k.result,q=r&&Object.keys(r)[0];kp=q?num(r[q].c[0],null):null}catch(e){}return{price,bid:wsFresh?(liveCbBid??num(t&&t.bid,null)):num(t&&t.bid,null),ask:wsFresh?(liveCbAsk??num(t&&t.ask,null)):num(t&&t.ask,null),price_source:proxyFresh?'brti-proxy':((refNow!==null||refFresh)?'coinbase-app-reference':((appNow!==null||appFresh)?'coinbase-app-spot':'coinbase-exchange-fallback')),price_age_ms:proxyFresh?(Date.now()-brtiProxyTime):(refNow!==null?0:(refFresh?(Date.now()-liveAppRefTime):(appNow!==null?0:(appFresh?(Date.now()-liveAppSpotTime):(wsFresh?(Date.now()-liveCbTime):null))))),brti_proxy:proxyFresh?brtiProxy:null,brti_spread:brtiSpread,brti_venues:Object.keys(brtiBook).filter(v=>Date.now()-brtiBook[v].ts<5000),coinbase_app_reference:refNow!==null?refNow:(refFresh?liveAppRef:null),coinbase_app_spot:appNow!==null?appNow:(appFresh?liveAppSpot:null),exchange_price:exchangePrice,candles,book_imbalance:bi,flow_imbalance:fi,kraken_price:kp,research_score:Number.isFinite(researchScore)?researchScore:0,research_age_ms:researchUpdated?Date.now()-researchUpdated:null,research_headlines:researchHeadlines.slice(0,5)}}
function predict(m,s){const c=s.candles,cl=c.map(x=>x.close);if(cl.length<8)throw Error('Not enough 1-minute candles yet');const rr=[];for(let i=1;i<cl.length;i++)if(cl[i-1])rr.push(cl[i]/cl[i-1]-1);let v=std(rr.slice(-20));if(v<.00001)v=.00001;const mom=clamp((.25*ret(cl,1)+.30*ret(cl,3)+.30*ret(cl,5)+.15*ret(cl,10))/v,-3,3),recent=cl.slice(-30),trend=clamp(((ema(recent,9)-ema(recent,21))/s.price)/v,-3,3);let vn=0,vd=0;for(const x of c.slice(-30)){const tp=(x.high+x.low+x.close)/3;vn+=tp*x.volume;vd+=x.volume}const vw=vd?vn/vd:mean(recent),mr=clamp(-(((s.price-vw)/s.price)/v)*.6,-2.5,2.5),research=Number.isFinite(s.research_score)?clamp(s.research_score,-2,2):0,mins=Math.max((Date.parse(m.end_utc)-Date.now())/60000,.25),sig=Math.max(s.price*v*Math.sqrt(mins),1),ptb=clamp((s.price-m.price_to_beat)/sig,-3,3),ms=m.yes_mid===null?0:clamp((m.yes_mid-.5)*4,-1.5,1.5),book=Number.isFinite(s.book_imbalance)?clamp(s.book_imbalance*2,-1.5,1.5):0,flow=Number.isFinite(s.flow_imbalance)?clamp(s.flow_imbalance*1.5,-1.5,1.5):0,cross=Number.isFinite(s.kraken_price)?clamp(((s.kraken_price-s.price)/s.price)/(v*2),-.8,.8):0,score=.28*mom+.17*trend+.11*mr+.22*ptb+.08*ms+.06*book+.05*flow+.03*cross,pick=score>=0?'OVER':'UNDER',confidence=Math.round(clamp(50+Math.tanh(Math.abs(score))*24,50,74));return{pick,score:+score.toFixed(4),model_confidence:confidence,entry_price:pick==='OVER'?(m.yes_ask??m.yes_mid):(m.no_ask??m.no_mid),signals:{momentum:+mom.toFixed(3),trend:+trend.toFixed(3),mean_reversion:+mr.toFixed(3),ptb_time:+ptb.toFixed(3),market:+ms.toFixed(3),book:+book.toFixed(3),flow:+flow.toFixed(3),cross:+cross.toFixed(3),research:+research.toFixed(3),vwap:+vw.toFixed(2)}}}
async function state(){const[m,s]=await Promise.all([market(),spot()]);if(m.price_to_beat===null)throw Error('Active contract has no authoritative Price to Beat');return{ok:true,variant:'chatgpt-kalshi-test',market:m,spot:s,prediction:predict(m,s),generated_at:new Date().toISOString()}}
const html=fs.readFileSync(path.join(__dirname,'public','index.html'),'utf8'),appJs=fs.readFileSync(path.join(__dirname,'public','app.js'),'utf8');
function send(res,code,data,type){type=type||'application/json; charset=utf-8';res.writeHead(code,{'Content-Type':type,'Cache-Control':'no-store'});res.end(type.startsWith('application/json')?JSON.stringify(data):data)}
http.createServer(async(req,res)=>{const u=new URL(req.url,'http://x');try{if(u.pathname==='/')return send(res,200,html,'text/html; charset=utf-8');if(u.pathname==='/app.js')return send(res,200,appJs,'application/javascript; charset=utf-8');if(u.pathname==='/api/price-stream'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-transform','Connection':'keep-alive','X-Accel-Buffering':'no'});res.write(': connected\n\n');priceClients.add(res);pushPrice();req.on('close',()=>priceClients.delete(res));return}if(u.pathname==='/api/coinbase-spot'){const app=await gj(CBAPP+'/v2/prices/BTC-USD/spot'),p=num(app&&app.data&&app.data.amount,null);return send(res,200,{ok:p!==null,price:p,source:'coinbase-app-spot',time:new Date().toISOString()})}if(u.pathname==='/health')return send(res,200,{ok:true,variant:'chatgpt-kalshi-test',time:new Date().toISOString()});if(u.pathname==='/api/session')return send(res,200,{ok:true,market:await market(),time:new Date().toISOString()});if(u.pathname==='/api/state')return send(res,200,await state());if(u.pathname==='/api/verify'){const t=u.searchParams.get('ticker');if(!t)return send(res,400,{ok:false,error:'ticker required'});return send(res,200,await strictVerifyTicker(t));}if(u.pathname==='/api/market'){const t=u.searchParams.get('ticker');if(!t)return send(res,400,{ok:false,error:'ticker required'});const p=await kj('/markets/'+encodeURIComponent(t));return send(res,200,{ok:true,market:pm(p.market||p)})}return send(res,404,{ok:false,error:'not found'})}catch(e){return send(res,500,{ok:false,error:e.message||String(e)})}}).listen(PORT,'0.0.0.0',()=>console.log('ChatGPT Kalshi Test on '+PORT));