const http=require('http'),fs=require('fs'),path=require('path'),URL=require('url').URL;
const PORT=process.env.PORT||10000,K1='https://external-api.kalshi.com/trade-api/v2',K2='https://api.elections.kalshi.com/trade-api/v2',CB='https://api.exchange.coinbase.com',CBAPP='https://api.coinbase.com',KR='https://api.kraken.com/0/public';
const H={'User-Agent':'ChatGPT-BTC15-Predictor/1.1 analytics-only','Accept':'application/json'};
let liveCbPrice=null,liveCbBid=null,liveCbAsk=null,liveCbTime=0,cbWs=null,liveAppSpot=null,liveAppSpotTime=0,liveAppRef=null,liveAppRefTime=0;const priceClients=new Set();function pushPrice(){const refFresh=Number.isFinite(liveAppRef)&&(Date.now()-liveAppRefTime<5000),spotFresh=Number.isFinite(liveAppSpot)&&(Date.now()-liveAppSpotTime<5000),p=refFresh?liveAppRef:(spotFresh?liveAppSpot:liveCbPrice),t=refFresh?liveAppRefTime:(spotFresh?liveAppSpotTime:liveCbTime);if(!Number.isFinite(p))return;const msg='data: '+JSON.stringify({price:p,time:t,source:refFresh?'coinbase-app-reference':(spotFresh?'coinbase-app-spot':'coinbase-exchange-fallback'),reference_price:liveAppRef,spot_price:liveAppSpot,exchange_price:liveCbPrice})+'\n\n';for(const r of priceClients){try{r.write(msg)}catch(e){priceClients.delete(r)}}}
function connectCoinbaseWs(){try{if(cbWs){try{cbWs.close()}catch(e){}}cbWs=new WebSocket('wss://ws-feed.exchange.coinbase.com');cbWs.onopen=()=>cbWs.send(JSON.stringify({type:'subscribe',product_ids:['BTC-USD'],channels:['ticker']}));cbWs.onmessage=(ev)=>{try{const m=JSON.parse(ev.data);if(m.type==='ticker'&&m.product_id==='BTC-USD'){const p=Number(m.price),b=Number(m.best_bid),a=Number(m.best_ask);if(Number.isFinite(p)){liveCbPrice=p;liveCbTime=Date.now()}if(Number.isFinite(b))liveCbBid=b;if(Number.isFinite(a))liveCbAsk=a;if(Number.isFinite(p))pushPrice()}}catch(e){}};cbWs.onclose=()=>setTimeout(connectCoinbaseWs,1000);cbWs.onerror=()=>{try{cbWs.close()}catch(e){}}}catch(e){setTimeout(connectCoinbaseWs,1500)}}
connectCoinbaseWs();
async function pollCoinbaseAppSpot(){try{const j=await gj(CBAPP+'/v2/prices/BTC-USD/spot'),p=num(j&&j.data&&j.data.amount,null);if(p!==null){liveAppSpot=p;liveAppSpotTime=Date.now();pushPrice()}}catch(e){}finally{setTimeout(pollCoinbaseAppSpot,1000)}}
async function pollCoinbaseAppRef(){try{const j=await gj(CBAPP+'/v2/exchange-rates?currency=BTC'),p=num(j&&j.data&&j.data.rates&&j.data.rates.USD,null);if(p!==null){liveAppRef=p;liveAppRefTime=Date.now();pushPrice()}}catch(e){}finally{setTimeout(pollCoinbaseAppRef,1000)}}
setTimeout(pollCoinbaseAppSpot,50);setTimeout(pollCoinbaseAppRef,100);
const num=(v,d=null)=>{const x=Number(v);return v===null||v===undefined||v===''||!Number.isFinite(x)?d:x};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
const std=a=>{if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))};
const ema=(a,p)=>{if(!a.length)return 0;let e=a[0],q=2/(p+1);for(let i=1;i<a.length;i++)e=q*a[i]+(1-q)*e;return e};
const ret=(a,n)=>a.length>n&&a[a.length-1-n]?a[a.length-1]/a[a.length-1-n]-1:0;
const mid=(b,a)=>Number.isFinite(b)&&Number.isFinite(a)?(b+a)/2:Number.isFinite(b)?b:Number.isFinite(a)?a:null;
async function gj(u){const c=new AbortController(),t=setTimeout(()=>c.abort(),7000);try{const r=await fetch(u,{headers:H,signal:c.signal});if(!r.ok)throw Error(r.status+' '+r.statusText);return await r.json()}finally{clearTimeout(t)}}
async function kj(p){try{return await gj(K1+p)}catch(e){return await gj(K2+p)}}
function pm(m){const close=new Date(m.close_time||m.expected_expiration_time||m.expiration_time||0);let open=new Date(m.open_time||close.getTime()-900000);if(!Number.isFinite(open.getTime()))open=new Date(close.getTime()-900000);let ptb=num(m.floor_strike,null);if(ptb===null)ptb=num(m.functional_strike,null);const lg=v=>{const x=num(v,null);return x===null?null:(x>1?x/100:x)};let yb=num(m.yes_bid_dollars,null),ya=num(m.yes_ask_dollars,null),nb=num(m.no_bid_dollars,null),na=num(m.no_ask_dollars,null);if(yb===null)yb=lg(m.yes_bid);if(ya===null)ya=lg(m.yes_ask);if(nb===null)nb=lg(m.no_bid);if(na===null)na=lg(m.no_ask);if(nb===null&&ya!==null)nb=1-ya;if(na===null&&yb!==null)na=1-yb;return{contract_id:String(m.ticker||''),start_utc:open.toISOString(),end_utc:close.toISOString(),price_to_beat:ptb,yes_bid:yb,yes_ask:ya,no_bid:nb,no_ask:na,yes_mid:mid(yb,ya),no_mid:mid(nb,na),result:String(m.result||'').toLowerCase(),status:String(m.status||'')}}
let marketCache=null,marketCacheAt=0;async function market(){if(marketCache&&Date.now()-marketCacheAt<600)return marketCache;const p=await kj('/markets?series_ticker=KXBTC15M&status=open&limit=200'),now=Date.now(),a=[];for(const m of(p.markets||[])){if(!String(m.ticker||'').startsWith('KXBTC15M-'))continue;const x=pm(m),o=Date.parse(x.start_utc),c=Date.parse(x.end_utc),left=(c-now)/1000;if(Number.isFinite(c)&&o<=now+30000&&left>=-15&&left<=960)a.push(x)}a.sort((x,y)=>Date.parse(x.end_utc)-Date.parse(y.end_utc));if(!a.length)throw Error('No active KXBTC15M market found');marketCache=a[0];marketCacheAt=Date.now();return marketCache}
async function spot(){const[ref,app,t,c,b,tr,k]=await Promise.all([gj(CBAPP+'/v2/exchange-rates?currency=BTC').catch(()=>null),gj(CBAPP+'/v2/prices/BTC-USD/spot').catch(()=>null),gj(CB+'/products/BTC-USD/ticker').catch(()=>null),gj(CB+'/products/BTC-USD/candles?granularity=60'),gj(CB+'/products/BTC-USD/book?level=2').catch(()=>null),gj(CB+'/products/BTC-USD/trades?limit=100').catch(()=>null),gj(KR+'/Ticker?pair=XBTUSD').catch(()=>null)]);const refNow=num(ref&&ref.data&&ref.data.rates&&ref.data.rates.USD,null),appNow=num(app&&app.data&&app.data.amount,null),refFresh=Number.isFinite(liveAppRef)&&(Date.now()-liveAppRefTime<5000),appFresh=Number.isFinite(liveAppSpot)&&(Date.now()-liveAppSpotTime<5000),wsFresh=Number.isFinite(liveCbPrice)&&(Date.now()-liveCbTime<5000),exchangePrice=wsFresh?liveCbPrice:num(t&&t.price,null),price=refNow!==null?refNow:(refFresh?liveAppRef:(appNow!==null?appNow:(appFresh?liveAppSpot:exchangePrice)));if(price===null)throw Error('Coinbase price unavailable');const candles=(Array.isArray(c)?c:[]).filter(x=>Array.isArray(x)&&x.length>=6).map(x=>({low:+x[1],high:+x[2],open:+x[3],close:+x[4],volume:+x[5]})).reverse();let bi=null;if(b){let bs=0,as=0;for(const x of(b.bids||[]).slice(0,25))bs+=+x[1]||0;for(const x of(b.asks||[]).slice(0,25))as+=+x[1]||0;if(bs+as)bi=(bs-as)/(bs+as)}let fi=null;if(Array.isArray(tr)){let buy=0,sell=0;for(const x of tr){const z=+x.size||0;if(x.side==='sell')buy+=z;else if(x.side==='buy')sell+=z}if(buy+sell)fi=(buy-sell)/(buy+sell)}let kp=null;try{const r=k&&k.result,q=r&&Object.keys(r)[0];kp=q?num(r[q].c[0],null):null}catch(e){}return{price,bid:wsFresh?(liveCbBid??num(t&&t.bid,null)):num(t&&t.bid,null),ask:wsFresh?(liveCbAsk??num(t&&t.ask,null)):num(t&&t.ask,null),coinbase_source:(refNow!==null||refFresh)?'coinbase-app-reference':((appNow!==null||appFresh)?'coinbase-app-spot':'coinbase-exchange-fallback'),coinbase_age_ms:refNow!==null?0:(refFresh?(Date.now()-liveAppRefTime):(appNow!==null?0:(appFresh?(Date.now()-liveAppSpotTime):(wsFresh?(Date.now()-liveCbTime):null)))),coinbase_app_reference:refNow!==null?refNow:(refFresh?liveAppRef:null),coinbase_app_spot:appNow!==null?appNow:(appFresh?liveAppSpot:null),exchange_price:exchangePrice,candles,book_imbalance:bi,flow_imbalance:fi,kraken_price:kp}}
function predict(m,s){const c=s.candles,cl=c.map(x=>x.close);if(cl.length<8)throw Error('Not enough 1-minute candles yet');const rr=[];for(let i=1;i<cl.length;i++)if(cl[i-1])rr.push(cl[i]/cl[i-1]-1);let v=std(rr.slice(-20));if(v<.00001)v=.00001;const mom=clamp((.25*ret(cl,1)+.30*ret(cl,3)+.30*ret(cl,5)+.15*ret(cl,10))/v,-3,3),recent=cl.slice(-30),trend=clamp(((ema(recent,9)-ema(recent,21))/s.price)/v,-3,3);let vn=0,vd=0;for(const x of c.slice(-30)){const tp=(x.high+x.low+x.close)/3;vn+=tp*x.volume;vd+=x.volume}const vw=vd?vn/vd:mean(recent),mr=clamp(-(((s.price-vw)/s.price)/v)*.6,-2.5,2.5),mins=Math.max((Date.parse(m.end_utc)-Date.now())/60000,.25),sig=Math.max(s.price*v*Math.sqrt(mins),1),ptb=clamp((s.price-m.price_to_beat)/sig,-3,3),ms=m.yes_mid===null?0:clamp((m.yes_mid-.5)*4,-1.5,1.5),book=Number.isFinite(s.book_imbalance)?clamp(s.book_imbalance*2,-1.5,1.5):0,flow=Number.isFinite(s.flow_imbalance)?clamp(s.flow_imbalance*1.5,-1.5,1.5):0,cross=Number.isFinite(s.kraken_price)?clamp(((s.kraken_price-s.price)/s.price)/(v*2),-.8,.8):0,score=.28*mom+.17*trend+.11*mr+.22*ptb+.08*ms+.06*book+.05*flow+.03*cross,pick=score>=0?'OVER':'UNDER',confidence=Math.round(clamp(50+Math.tanh(Math.abs(score))*24,50,74));return{pick,score:+score.toFixed(4),model_confidence:confidence,entry_price:pick==='OVER'?(m.yes_ask??m.yes_mid):(m.no_ask??m.no_mid),signals:{momentum:+mom.toFixed(3),trend:+trend.toFixed(3),mean_reversion:+mr.toFixed(3),ptb_time:+ptb.toFixed(3),market:+ms.toFixed(3),book:+book.toFixed(3),flow:+flow.toFixed(3),vwap:+vw.toFixed(2)}}}
async function state(){const[m,s]=await Promise.all([market(),spot()]);if(m.price_to_beat===null)throw Error('Active contract has no authoritative Price to Beat');return{ok:true,market:m,spot:s,prediction:predict(m,s),generated_at:new Date().toISOString()}}
const html=fs.readFileSync(path.join(__dirname,'public','index.html'),'utf8');
function send(res,code,data,type){type=type||'application/json; charset=utf-8';res.writeHead(code,{'Content-Type':type,'Cache-Control':'no-store'});res.end(type.startsWith('application/json')?JSON.stringify(data):data)}
http.createServer(async(req,res)=>{const u=new URL(req.url,'http://x');try{if(u.pathname==='/')return send(res,200,html,'text/html; charset=utf-8');if(u.pathname==='/api/price-stream'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-transform','Connection':'keep-alive','X-Accel-Buffering':'no'});res.write(': connected\n\n');priceClients.add(res);pushPrice();req.on('close',()=>priceClients.delete(res));return}if(u.pathname==='/api/coinbase-spot'){const app=await gj(CBAPP+'/v2/prices/BTC-USD/spot'),p=num(app&&app.data&&app.data.amount,null);return send(res,200,{ok:p!==null,price:p,source:'coinbase-app-spot',time:new Date().toISOString()})}if(u.pathname==='/health')return send(res,200,{ok:true,time:new Date().toISOString()});if(u.pathname==='/api/session')return send(res,200,{ok:true,market:await market(),time:new Date().toISOString()});if(u.pathname==='/api/state')return send(res,200,await state());if(u.pathname==='/api/market'){const t=u.searchParams.get('ticker');if(!t)return send(res,400,{ok:false,error:'ticker required'});const p=await kj('/markets/'+encodeURIComponent(t));return send(res,200,{ok:true,market:pm(p.market||p)})}return send(res,404,{ok:false,error:'not found'})}catch(e){return send(res,500,{ok:false,error:e.message||String(e)})}}).listen(PORT,'0.0.0.0',()=>console.log('BTC15 Predictor on '+PORT));